### ISSUE TITLE
reversed conditional

### ISSUE THREAD

**Issue by elktamer** [SemkoDev/nelson.gui#1]
Is the conditional for the IRI health check backwards for a reason? 

            `<StatusListItem label='Is IRI Healthy' value={nelsonData.isIRIHealthy ? 'no' : 'yes'} icon='heartbeat'/>`

It says no with the nelsonData member "isIRIHealthy: true"

**Comment by romansemko** [comment]
Good catch! Just filed a bug #2 regarding this as well. Will mark it as duplicate.
