### ISSUE TITLE
Invalid docker image in Docker Hub

### ISSUE THREAD

**Issue by akomelj** [SemkoDev/nelson.gui#6]
Is it possible that Docker Hub image for nelson.gui is, at the time of writing (Jan 5), actually an image of Nelson instead of Nelson GUI?

If I pull and run the image, /usr/local/bin/nelson is started, listening on default ports. I have tried this on 2 different servers so I doubt this is error on my side.

docker run -it romansemko/nelson.gui

**Comment by Andersmholmgren** [comment]
Damn I just realised this too. Wasted an hour or so debugging before I realised the image runs nelson.cli

**Comment by romansemko** [comment]
Fixed. Thanks for the tip @akomelj ! Sorry for the delay. :-)
